services:
  redis:
    image: redis:8.0
    container_name: redis-cache
    ports:
      - "127.0.0.1:6379:6379" # Solo host local
    restart: unless-stopped
    volumes:
      - redis_data:/data # Para que la cach√© no se borre al reiniciar el contenedor

volumes:
  redis_data: